---
title: "HARTMANN"
format: html
editor: visual
---

## Question 1 : 
```{r}
#| message: false
here::i_am("grades-eval.Rproj")
library(here)
library(vroom)
library(dplyr)
library(tidyr)
library(stringr)
```

```{r}
grades <- vroom(here("grades (2).csv"))
```
## Question 2 
```{r}
grades |>
  nrow()
```
The data set contains 64686 grades. 

## Question 3 
```{r}
grades |> 
  distinct(id) |>
  nrow()
```
The data set contains 938 students. 

## Question 4 : 
```{r}
grades |> 
  group_by(id, group)|> 
  distinct(id)|> 
  slice_tail(n = 5) |>
knitr::kable()
```

## Question 5 : 
```{r}
library(ggplot2)
ggplot(grades, aes(x = group)) +
  geom_bar() +
  labs(
    title = "Number of Students per Group",
    x = "Group",
    y = "Number of Students"
  )
```


##Question 6 
```{r}
grades |> 
  group_by(group)|> 
   filter(module == "Hunting and Gathering Skills")|>
 summarise(average_of_the_grades_in_Hunting_and_Gathering_Skills = mean(grade))
 
```

## Question 7 : 
```{r}

```

## Question 8 : 
```{r}
grades |> 
  group_by(id, group)|>
  summarise (
     "number of grades per student" = n(),
min = min(grade),
    max= max(grade),
    mean = mean(grade),
    meadian = median(grade))|>
   slice_tail(n = 5) |>
knitr::kable()  
```

```{r}

```

